import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from './Navbar';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ikaera  App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
          <SignedIn >
            <h1>Bienvenue, vous êtes connecté !</h1>
          
            {/* Contenu sécurisé */}
          </SignedIn>
          <SignedOut>
            <div className='flex justify-center items-center flex-col row-span-2'>
              <UserButton/>
              <h1>Veuillez vous connecter</h1>
              <Link href='/sign-in' className='p- bg-blue-500 m-2'> M'inscrire</Link>
              <Link href='/contact' className='p- bg-blue-500 m-2'> contact</Link>
            </div>
          </SignedOut>
          </header>
          <main style={{ paddingTop: '10px' }}>
              {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
